
modLoader="javafml" #mandatory
loaderVersion="[38,)" #mandatory
license="MIT"

[[mods]] #mandatory
modId="bygonenether" #mandatory
version="1.0.1" #mandatory
displayName="Bygone Nether" #mandatory
logoFile="bygonenether.png" #optional
#credits="" #optional
authors="Izofar" #optional

description="Remnants of the nether dimension's ancient history"

[[dependencies.bygonenether]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"

[[dependencies.repurposed_structures]]
    modId="forge"
    mandatory=true
    versionRange="[40.0.0,)"
