
modLoader="javafml" #mandatory
loaderVersion="[36.2,)" #mandatory
license="MIT"

[[mods]] #mandatory
modId="bygonenether" #mandatory
version="1.1.1" #mandatory
displayName="Bygone Nether" #mandatory
logoFile="bygonenether.png" #optional
#credits="" #optional
authors="Izofar" #optional

description="Remnants of the nether dimension's ancient history"

[[dependencies.bygonenether]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17.0)"
    ordering="NONE"
    side="BOTH"

[[dependencies.bygonenether]]
    modId="forge"
    mandatory=true
    versionRange="[36.2.17,)"