
modLoader="javafml" #mandatory
loaderVersion="[41,)" #mandatory
license="MIT"

[[mods]] #mandatory
modId="bygonenether" #mandatory
version="1.2" #mandatory
displayName="Bygone Nether" #mandatory
logoFile="bygonenether.png" #optional
#credits="" #optional
authors="Izofar" #optional

description="Remnants of the nether dimension's ancient history"

[[dependencies.bygonenether]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19,1.20)"

[[dependencies.bygonenether]]
    modId="forge"
    mandatory=true
    versionRange="[41.0.21,)"
